# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://zephyrtransport.github.io/scoping-buddy
baseurl: /scoping-buddy
zephyr-url: http://zephyrtransport.org
title: Scoping Buddy for Travel Analysis
short-title: Scoping Buddy

email: info@zephyrtransport.org
author: Elizabeth Sall
description: The Zephyr Foundation’s mission is to advance rigorous transportation and land use decision-making for the public good by advocating for and supporting improved travel analysis and facilitating its implementation.
copyright: 'Copyright &copy; 2019 Zephyr Foundation. All Rights Reserved.'
credits: 'Site created by Elizabeth Sall, UrbanLabs LLC'

collections:
    projects:
        output: true

display_tags: [RFP]
empty_array: []


# ----------------------- #
#   Look Settings         #
# ----------------------- #

top-bg-img:
bottom-bh-img:
highlight-color: 0daee1       #turquoise blue
dark-gray-color: 4e4f58       #dark gray
background-highlight: fafafa    #light gray - blueish
highlight-text: f8f8f8          #light gray


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   Social                #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/zephyrtransport
  - title: github
    url: https://github.com/zephyrtransport
  - title: email
    url: http://eepurl.com/ccQL7z
